# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(271, 75)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_choose_hex = QtWidgets.QToolButton(self.centralwidget)
        self.btn_choose_hex.setGeometry(QtCore.QRect(10, 10, 91, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btn_choose_hex.setFont(font)
        self.btn_choose_hex.setObjectName("btn_choose_hex")
        self.cur_progress = QtWidgets.QProgressBar(self.centralwidget)
        self.cur_progress.setGeometry(QtCore.QRect(110, 10, 151, 23))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.cur_progress.setFont(font)
        self.cur_progress.setProperty("value", 0)
        self.cur_progress.setObjectName("cur_progress")
        self.lb_show = QtWidgets.QLabel(self.centralwidget)
        self.lb_show.setGeometry(QtCore.QRect(10, 40, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lb_show.setFont(font)
        self.lb_show.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_show.setObjectName("lb_show")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "McuBurner"))
        self.btn_choose_hex.setText(_translate("MainWindow", "CHOOSE_HEX"))
        self.lb_show.setText(_translate("MainWindow", " ------  ------   ------   ------    ------"))
